import Permission from "../modules/auth/Permission.js";
import { AUTHZ_ACTIONS } from "./actions.js";

export const SCOPE_TYPES = Object.freeze({
  GLOBAL: "GLOBAL",
  BRANCH: "BRANCH",
  SELF: "SELF",
  TASK: "TASK",
});

export const PERMISSION_CATALOG_DEFINITIONS = Object.freeze([
  {
    key: AUTHZ_ACTIONS.ANALYTICS_READ_BRANCH,
    module: "analytics",
    action: "read.branch",
    scopeType: SCOPE_TYPES.BRANCH,
    description: "Read analytics for active branch",
    isSensitive: false,
  },
  {
    key: AUTHZ_ACTIONS.ANALYTICS_READ_ASSIGNED,
    module: "analytics",
    action: "read.assigned",
    scopeType: SCOPE_TYPES.BRANCH,
    description: "Read analytics for assigned branches",
    isSensitive: false,
  },
  {
    key: AUTHZ_ACTIONS.ANALYTICS_READ_GLOBAL,
    module: "analytics",
    action: "read.global",
    scopeType: SCOPE_TYPES.GLOBAL,
    description: "Read analytics across all branches",
    isSensitive: true,
  },
  {
    key: AUTHZ_ACTIONS.ANALYTICS_READ_PERSONAL,
    module: "analytics",
    action: "read.personal",
    scopeType: SCOPE_TYPES.SELF,
    description: "Read personal analytics",
    isSensitive: false,
  },
  {
    key: AUTHZ_ACTIONS.ANALYTICS_MANAGE_GLOBAL,
    module: "analytics",
    action: "manage.global",
    scopeType: SCOPE_TYPES.GLOBAL,
    description: "Manage global analytics datasets",
    isSensitive: true,
  },
  {
    key: AUTHZ_ACTIONS.USERS_READ_BRANCH,
    module: "users",
    action: "read.branch",
    scopeType: SCOPE_TYPES.BRANCH,
    description: "Read users in branch scope",
    isSensitive: true,
  },
  {
    key: AUTHZ_ACTIONS.USERS_MANAGE_BRANCH,
    module: "users",
    action: "manage.branch",
    scopeType: SCOPE_TYPES.BRANCH,
    description: "Create/update users in branch scope",
    isSensitive: true,
  },
  {
    key: AUTHZ_ACTIONS.USERS_MANAGE_GLOBAL,
    module: "users",
    action: "manage.global",
    scopeType: SCOPE_TYPES.GLOBAL,
    description: "Create/update users across all branches",
    isSensitive: true,
  },
  {
    key: AUTHZ_ACTIONS.ACCOUNT_PROFILE_UPDATE_SELF,
    module: "account",
    action: "profile.update.self",
    scopeType: SCOPE_TYPES.SELF,
    description: "Update own profile",
    isSensitive: false,
  },
  {
    key: AUTHZ_ACTIONS.ACCOUNT_ADDRESS_MANAGE_SELF,
    module: "account",
    action: "address.manage.self",
    scopeType: SCOPE_TYPES.SELF,
    description: "Manage own saved addresses",
    isSensitive: false,
  },
  {
    key: AUTHZ_ACTIONS.CART_MANAGE_SELF,
    module: "cart",
    action: "manage.self",
    scopeType: SCOPE_TYPES.SELF,
    description: "Manage own cart",
    isSensitive: false,
  },
  {
    key: AUTHZ_ACTIONS.ORDERS_READ,
    module: "orders",
    action: "read",
    scopeType: SCOPE_TYPES.BRANCH,
    description: "Read order data",
    isSensitive: false,
  },
  {
    key: AUTHZ_ACTIONS.ORDERS_WRITE,
    module: "orders",
    action: "write",
    scopeType: SCOPE_TYPES.BRANCH,
    description: "Create or update order data",
    isSensitive: true,
  },
  {
    key: AUTHZ_ACTIONS.ORDER_AUDIT_READ,
    module: "order",
    action: "audit.read",
    scopeType: SCOPE_TYPES.BRANCH,
    description: "Read order audit logs",
    isSensitive: true,
  },
  {
    key: AUTHZ_ACTIONS.ORDER_VIEW_SELF,
    module: "order",
    action: "view.self",
    scopeType: SCOPE_TYPES.SELF,
    description: "View own orders",
    isSensitive: false,
  },
  {
    key: AUTHZ_ACTIONS.ORDER_VIEW_ASSIGNED,
    module: "order",
    action: "view.assigned",
    scopeType: SCOPE_TYPES.TASK,
    description: "View assigned delivery orders",
    isSensitive: false,
  },
  {
    key: AUTHZ_ACTIONS.ORDER_ASSIGN_CARRIER,
    module: "order",
    action: "assign.carrier",
    scopeType: SCOPE_TYPES.BRANCH,
    description: "Assign carrier or shipper to an order",
    isSensitive: true,
  },
  {
    key: AUTHZ_ACTIONS.ORDER_ASSIGN_STORE,
    module: "order",
    action: "assign.store",
    scopeType: SCOPE_TYPES.BRANCH,
    description: "Assign a branch to an order",
    isSensitive: true,
  },
  {
    key: AUTHZ_ACTIONS.ORDER_STATUS_MANAGE,
    module: "order",
    action: "status.manage",
    scopeType: SCOPE_TYPES.BRANCH,
    description: "Manage order status workflow",
    isSensitive: true,
  },
  {
    key: AUTHZ_ACTIONS.ORDER_STATUS_MANAGE_WAREHOUSE,
    module: "order",
    action: "status.manage.warehouse",
    scopeType: SCOPE_TYPES.BRANCH,
    description: "Manage warehouse order status workflow",
    isSensitive: true,
  },
  {
    key: AUTHZ_ACTIONS.ORDER_STATUS_MANAGE_TASK,
    module: "order",
    action: "status.manage.task",
    scopeType: SCOPE_TYPES.TASK,
    description: "Manage assigned delivery order status workflow",
    isSensitive: true,
  },
  {
    key: AUTHZ_ACTIONS.ORDER_STATUS_MANAGE_POS,
    module: "order",
    action: "status.manage.pos",
    scopeType: SCOPE_TYPES.BRANCH,
    description: "Manage in-store order handover workflow",
    isSensitive: true,
  },
  {
    key: AUTHZ_ACTIONS.ORDER_PICK_COMPLETE_INSTORE,
    module: "order",
    action: "pick.complete.instore",
    scopeType: SCOPE_TYPES.BRANCH,
    description: "Complete in-store picking workflow",
    isSensitive: true,
  },
  {
    key: AUTHZ_ACTIONS.ORDER_PICKER_ASSIGN_INSTORE,
    module: "order",
    action: "picker.assign.instore",
    scopeType: SCOPE_TYPES.BRANCH,
    description: "Assign in-store order picker",
    isSensitive: true,
  },
  {
    key: AUTHZ_ACTIONS.INVENTORY_READ,
    module: "inventory",
    action: "read",
    scopeType: SCOPE_TYPES.BRANCH,
    description: "Read inventory data",
    isSensitive: false,
  },
  {
    key: AUTHZ_ACTIONS.INVENTORY_WRITE,
    module: "inventory",
    action: "write",
    scopeType: SCOPE_TYPES.BRANCH,
    description: "Adjust inventory",
    isSensitive: true,
  },
  {
    key: AUTHZ_ACTIONS.DEVICE_READ,
    module: "device",
    action: "read",
    scopeType: SCOPE_TYPES.BRANCH,
    description: "Read serialized device data",
    isSensitive: false,
  },
  {
    key: AUTHZ_ACTIONS.DEVICE_WRITE,
    module: "device",
    action: "write",
    scopeType: SCOPE_TYPES.BRANCH,
    description: "Create or update serialized devices",
    isSensitive: true,
  },
  {
    key: AUTHZ_ACTIONS.WARRANTY_READ,
    module: "warranty",
    action: "read",
    scopeType: SCOPE_TYPES.BRANCH,
    description: "Read warranty records",
    isSensitive: false,
  },
  {
    key: AUTHZ_ACTIONS.WARRANTY_WRITE,
    module: "warranty",
    action: "write",
    scopeType: SCOPE_TYPES.BRANCH,
    description: "Manage warranty records",
    isSensitive: true,
  },
  {
    key: AUTHZ_ACTIONS.PRODUCT_READ,
    module: "product",
    action: "read",
    scopeType: SCOPE_TYPES.BRANCH,
    description: "Read product catalog",
    isSensitive: false,
  },
  {
    key: AUTHZ_ACTIONS.PRODUCT_CREATE,
    module: "product",
    action: "create",
    scopeType: SCOPE_TYPES.BRANCH,
    description: "Create products",
    isSensitive: true,
  },
  {
    key: AUTHZ_ACTIONS.PRODUCT_UPDATE,
    module: "product",
    action: "update",
    scopeType: SCOPE_TYPES.BRANCH,
    description: "Update products",
    isSensitive: true,
  },
  {
    key: AUTHZ_ACTIONS.PRODUCT_DELETE,
    module: "product",
    action: "delete",
    scopeType: SCOPE_TYPES.BRANCH,
    description: "Delete products",
    isSensitive: true,
  },
  {
    key: AUTHZ_ACTIONS.BRAND_MANAGE,
    module: "brand",
    action: "manage",
    scopeType: SCOPE_TYPES.BRANCH,
    description: "Manage brands",
    isSensitive: true,
  },
  {
    key: AUTHZ_ACTIONS.PRODUCT_TYPE_MANAGE,
    module: "product_type",
    action: "manage",
    scopeType: SCOPE_TYPES.BRANCH,
    description: "Manage product types",
    isSensitive: true,
  },
  {
    key: AUTHZ_ACTIONS.WAREHOUSE_READ,
    module: "warehouse",
    action: "read",
    scopeType: SCOPE_TYPES.BRANCH,
    description: "Read warehouse operations",
    isSensitive: false,
  },
  {
    key: AUTHZ_ACTIONS.WAREHOUSE_WRITE,
    module: "warehouse",
    action: "write",
    scopeType: SCOPE_TYPES.BRANCH,
    description: "Operate warehouse processes",
    isSensitive: true,
  },
  {
    key: AUTHZ_ACTIONS.TRANSFER_CREATE,
    module: "transfer",
    action: "create",
    scopeType: SCOPE_TYPES.BRANCH,
    description: "Create stock transfer",
    isSensitive: true,
  },
  {
    key: AUTHZ_ACTIONS.TRANSFER_APPROVE,
    module: "transfer",
    action: "approve",
    scopeType: SCOPE_TYPES.BRANCH,
    description: "Approve stock transfer",
    isSensitive: true,
  },
  {
    key: AUTHZ_ACTIONS.TRANSFER_SHIP,
    module: "transfer",
    action: "ship",
    scopeType: SCOPE_TYPES.BRANCH,
    description: "Ship stock transfer",
    isSensitive: true,
  },
  {
    key: AUTHZ_ACTIONS.TRANSFER_RECEIVE,
    module: "transfer",
    action: "receive",
    scopeType: SCOPE_TYPES.BRANCH,
    description: "Receive stock transfer",
    isSensitive: true,
  },
  {
    key: AUTHZ_ACTIONS.TRANSFER_READ,
    module: "transfer",
    action: "read",
    scopeType: SCOPE_TYPES.BRANCH,
    description: "Read stock transfer",
    isSensitive: false,
  },
  {
    key: AUTHZ_ACTIONS.STORE_MANAGE,
    module: "store",
    action: "manage",
    scopeType: SCOPE_TYPES.BRANCH,
    description: "Manage stores",
    isSensitive: true,
  },
  {
    key: AUTHZ_ACTIONS.CONTENT_MANAGE,
    module: "content",
    action: "manage",
    scopeType: SCOPE_TYPES.BRANCH,
    description: "Manage homepage and short video content",
    isSensitive: true,
  },
  {
    key: AUTHZ_ACTIONS.MONITORING_READ,
    module: "monitoring",
    action: "read",
    scopeType: SCOPE_TYPES.BRANCH,
    description: "Read rollout and monitoring telemetry",
    isSensitive: true,
  },
  {
    key: AUTHZ_ACTIONS.PROMOTION_APPLY_SELF,
    module: "promotion",
    action: "apply.self",
    scopeType: SCOPE_TYPES.SELF,
    description: "Apply promotion codes to own order",
    isSensitive: false,
  },
  {
    key: AUTHZ_ACTIONS.PROMOTION_MANAGE,
    module: "promotion",
    action: "manage",
    scopeType: SCOPE_TYPES.BRANCH,
    description: "Manage promotions",
    isSensitive: true,
  },
  {
    key: AUTHZ_ACTIONS.REVIEW_CREATE_SELF,
    module: "review",
    action: "create.self",
    scopeType: SCOPE_TYPES.SELF,
    description: "Create own review",
    isSensitive: false,
  },
  {
    key: AUTHZ_ACTIONS.REVIEW_UPDATE_SELF,
    module: "review",
    action: "update.self",
    scopeType: SCOPE_TYPES.SELF,
    description: "Update own review",
    isSensitive: false,
  },
  {
    key: AUTHZ_ACTIONS.REVIEW_DELETE_SELF,
    module: "review",
    action: "delete.self",
    scopeType: SCOPE_TYPES.SELF,
    description: "Delete own review",
    isSensitive: false,
  },
  {
    key: AUTHZ_ACTIONS.REVIEW_LIKE_SELF,
    module: "review",
    action: "like.self",
    scopeType: SCOPE_TYPES.SELF,
    description: "Like or unlike a review as self",
    isSensitive: false,
  },
  {
    key: AUTHZ_ACTIONS.REVIEW_UPLOAD_SELF,
    module: "review",
    action: "upload.self",
    scopeType: SCOPE_TYPES.SELF,
    description: "Request review upload signature for own content",
    isSensitive: false,
  },
  {
    key: AUTHZ_ACTIONS.REVIEW_REPLY,
    module: "review",
    action: "reply",
    scopeType: SCOPE_TYPES.BRANCH,
    description: "Reply to reviews as staff",
    isSensitive: true,
  },
  {
    key: AUTHZ_ACTIONS.REVIEW_MODERATE,
    module: "review",
    action: "moderate",
    scopeType: SCOPE_TYPES.BRANCH,
    description: "Moderate or hide reviews",
    isSensitive: true,
  },
  {
    key: AUTHZ_ACTIONS.TASK_READ,
    module: "task",
    action: "read",
    scopeType: SCOPE_TYPES.SELF,
    description: "Read assigned task",
    isSensitive: false,
  },
  {
    key: AUTHZ_ACTIONS.TASK_UPDATE,
    module: "task",
    action: "update",
    scopeType: SCOPE_TYPES.TASK,
    description: "Update assigned task",
    isSensitive: false,
  },
  {
    key: AUTHZ_ACTIONS.POS_ORDER_CREATE,
    module: "pos",
    action: "order.create",
    scopeType: SCOPE_TYPES.BRANCH,
    description: "Create in-store POS order",
    isSensitive: true,
  },
  {
    key: AUTHZ_ACTIONS.POS_ORDER_READ_SELF,
    module: "pos",
    action: "order.read.self",
    scopeType: SCOPE_TYPES.SELF,
    description: "Read own POS orders",
    isSensitive: false,
  },
  {
    key: AUTHZ_ACTIONS.POS_ORDER_READ_BRANCH,
    module: "pos",
    action: "order.read.branch",
    scopeType: SCOPE_TYPES.BRANCH,
    description: "Read branch POS orders",
    isSensitive: true,
  },
  {
    key: AUTHZ_ACTIONS.POS_PAYMENT_PROCESS,
    module: "pos",
    action: "payment.process",
    scopeType: SCOPE_TYPES.BRANCH,
    description: "Process POS payment",
    isSensitive: true,
  },
  {
    key: AUTHZ_ACTIONS.POS_ORDER_CANCEL,
    module: "pos",
    action: "order.cancel",
    scopeType: SCOPE_TYPES.BRANCH,
    description: "Cancel POS order",
    isSensitive: true,
  },
  {
    key: AUTHZ_ACTIONS.POS_ORDER_FINALIZE,
    module: "pos",
    action: "order.finalize",
    scopeType: SCOPE_TYPES.BRANCH,
    description: "Finalize POS order",
    isSensitive: true,
  },
  {
    key: AUTHZ_ACTIONS.POS_VAT_ISSUE,
    module: "pos",
    action: "vat.issue",
    scopeType: SCOPE_TYPES.BRANCH,
    description: "Issue POS VAT invoice",
    isSensitive: true,
  },
  {
    key: AUTHZ_ACTIONS.CONTEXT_SWITCH_BRANCH,
    module: "context",
    action: "switch.branch",
    scopeType: SCOPE_TYPES.BRANCH,
    description: "Switch active branch context",
    isSensitive: true,
  },
  {
    key: AUTHZ_ACTIONS.CONTEXT_SIMULATE_BRANCH,
    module: "context",
    action: "simulate.branch",
    scopeType: SCOPE_TYPES.GLOBAL,
    description: "Simulate branch context",
    isSensitive: true,
  },
]);

const normalizePermissionKey = (value) => String(value || "").trim().toLowerCase();

export const getCatalogDefinitionByKey = () => {
  const map = new Map();
  for (const definition of PERMISSION_CATALOG_DEFINITIONS) {
    map.set(normalizePermissionKey(definition.key), definition);
  }
  return map;
};

export const ensurePermissionCatalogSeeded = async () => {
  if (!PERMISSION_CATALOG_DEFINITIONS.length) {
    return 0;
  }

  const operations = PERMISSION_CATALOG_DEFINITIONS.map((definition) => ({
    updateOne: {
      filter: { key: normalizePermissionKey(definition.key) },
      update: {
        $set: {
          key: normalizePermissionKey(definition.key),
          module: definition.module,
          action: definition.action,
          scopeType: definition.scopeType,
          defaultScope: definition.defaultScope || definition.scopeType,
          resourceType: definition.resourceType || definition.module,
          description: definition.description || "",
          isSensitive: Boolean(definition.isSensitive),
          isActive: true,
          "metadata.source": "SYSTEM_CATALOG",
        },
      },
      upsert: true,
    },
  }));

  await Permission.bulkWrite(operations, { ordered: false });
  return operations.length;
};

export const getPermissionCatalog = async ({ includeInactive = false } = {}) => {
  const filter = includeInactive ? {} : { isActive: true };
  const items = await Permission.find(filter)
    .select(
      "_id key module action scopeType defaultScope resourceType description isSensitive isActive"
    )
    .sort({ module: 1, key: 1 })
    .lean();
  return items;
};

export default {
  SCOPE_TYPES,
  PERMISSION_CATALOG_DEFINITIONS,
  ensurePermissionCatalogSeeded,
  getPermissionCatalog,
  getCatalogDefinitionByKey,
};
